// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HelloService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::HelloThrift::Interface;

class HelloServiceHandler : virtual public HelloServiceIf {
 public:
  HelloServiceHandler() {
    // Your initialization goes here
  }

  void HelloString(std::string& _return, const std::string& para) {
    // Your implementation goes here
    printf("HelloString\n");
  }

  int32_t HelloInt(const int32_t para) {
    // Your implementation goes here
    printf("HelloInt\n");
  }

  bool HelloBoolean(const bool para) {
    // Your implementation goes here
    printf("HelloBoolean\n");
  }

  void HelloVoid() {
    // Your implementation goes here
    printf("HelloVoid\n");
  }

  void HelloNull(std::string& _return) {
    // Your implementation goes here
    printf("HelloNull\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<HelloServiceHandler> handler(new HelloServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new HelloServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

