// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#if 0
#include "HelloService.h"
#include <thrift/transport/TBufferTransports.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PlatformThreadFactory.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>
#include <thrift/TToString.h>
#include <thrift/stdcxx.h>

#include <iostream>
#include <stdexcept>
#include <sstream>

//using namespace ::apache::thrift;
//using namespace ::apache::thrift::protocol;
//using namespace ::apache::thrift::transport;
//using namespace ::apache::thrift::server;
//
//using boost::shared_ptr;
//
//using namespace  ::HelloThrift::Interface;

using namespace std;
using namespace apache::thrift;
using namespace apache::thrift::concurrency;
using namespace apache::thrift::protocol;
using namespace apache::thrift::transport;
using namespace apache::thrift::server;

//using namespace tutorial;
//using namespace shared;
//using namespace  ::HelloThrift::Interface;
using namespace  HelloThrift;
using namespace  HelloThrift::Interface;;

class HelloServiceHandler : virtual public HelloServiceIf {
 public:
  HelloServiceHandler() {
    // Your initialization goes here
  }

  void HelloString(std::string& _return, const std::string& para) {
    // Your implementation goes here
    printf("HelloString,I got your name %s\n",para.c_str());
	_return = "give you back";
  }

  int32_t HelloInt(const int32_t para) {
    // Your implementation goes here
    printf("HelloInt\n");
	return para;
  }

  bool HelloBoolean(const bool para) {
    // Your implementation goes here
    printf("HelloBoolean\n");
	return para;
  }

  void HelloVoid() {
    // Your implementation goes here
    printf("HelloVoid\n");
  }

  void HelloNull(std::string& _return) {
    // Your implementation goes here
    printf("HelloNull\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HelloServiceHandler> handler(new HelloServiceHandler());
  shared_ptr<TProcessor> processor(new HelloServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

#endif


#include "HelloService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/async/TEvhttpServer.h>
#include <thrift/async/TAsyncProtocolProcessor.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::async;

class HelloServiceHandler : virtual public HelloServiceIf {
public:
	HelloServiceHandler() {
		// Your initialization goes here
	}

	int16_t addxy(const int16_t x, const int16_t y) {
		// Your implementation goes here
		return x + y;
		printf("addxy\n");
	}

};

class HelloServiceAsyncHandler : public HelloServiceCobSvIf {
public:
	HelloServiceAsyncHandler() {
		syncHandler_ = std::auto_ptr<HelloServiceHandler>(new HelloServiceHandler);
		// Your initialization goes here
	}
	//virtual ~HelloServiceAsyncHandler();

	void addxy(::apache::thrift::stdcxx::function<void(int16_t const& _return)> cob, const int16_t x, const int16_t y) {
		int16_t _return = 0;
		_return = syncHandler_->addxy(x, y);
		return cob(_return);
	}

protected:
	std::auto_ptr<HelloServiceHandler> syncHandler_;
};

#if 0
int main(int argc, char **argv) 
{
	printf("hello i am server\n");
	int port = 9090;
	::apache::thrift::stdcxx::shared_ptr<HelloServiceHandler> handler(new HelloServiceHandler());
	::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new HelloServiceProcessor(handler));
	::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
	::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
	::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

	TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
	server.serve();
	return 0;
}
#endif

int main(int argc, char **argv)
{
	printf("hello i am server\n");
	::apache::thrift::stdcxx::shared_ptr<TAsyncProcessor> underlying_pro(new HelloServiceAsyncProcessor(::apache::thrift::stdcxx::shared_ptr<HelloServiceCobSvIf>(new HelloServiceAsyncHandler())));
	::apache::thrift::stdcxx::shared_ptr<TAsyncBufferProcessor> processor(new TAsyncProtocolProcessor(underlying_pro, ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory>(new TBinaryProtocolFactory())));

	TEvhttpServer server(processor, 9090);
	server.serve();
	return 0;
}
